name: Build snap

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Also allow manual triggering
  workflow_dispatch:

env:
  ARTIFACT_AMD64: tf-label-image_${{ github.run_number}}_amd64
  ARTIFACT_ARM64: tf-label-image_${{ github.run_number}}_arm64

jobs:
  build-amd64:
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_AMD64 }}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
